// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT73WuViCvX_KJYO0ndW6ZbrAI7a-dixw',
    appId: '1:434836595313:web:cdd0ec03e08874c68bf1d0',
    messagingSenderId: '434836595313',
    projectId: 'medisenseapp-ece7b',
    authDomain: 'medisenseapp-ece7b.firebaseapp.com',
    storageBucket: 'medisenseapp-ece7b.appspot.com',
    measurementId: 'G-96CBWZZ2NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvo7s45BOuTKZH8QY-9GT8YX8b0VWHuKg',
    appId: '1:434836595313:android:b22c1001ecb7e54b8bf1d0',
    messagingSenderId: '434836595313',
    projectId: 'medisenseapp-ece7b',
    storageBucket: 'medisenseapp-ece7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdVXGB2-fKRqLatIfTuVbLcaxWh5Nh8z0',
    appId: '1:434836595313:ios:f98dc9892d08bce98bf1d0',
    messagingSenderId: '434836595313',
    projectId: 'medisenseapp-ece7b',
    storageBucket: 'medisenseapp-ece7b.appspot.com',
    iosBundleId: 'com.example.medisenseApp',
  );
}
